version: '3.8'
services:
  node:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '${PORT}:3000'
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'